### PR TITLE
(Re-Do) Resolved issue #4

### PR DESCRIPTION
**Pull request by camaechi**
Pull request #51  reverted some of the changes made by pull request #22 because it was merged without being approved. This pull request adds the remaining changes that #22 made again and now needs to be approved.

### CODE REVIEW

**Review by TonePoems — COMMENTED** [review]
Is this the full PR? Doesnt look like the whole feature unless it got lost in the shuffle somewhere.

**Comment by camaechi** [comment]
For some reason, the revert pr removed only a partial amount of the code, I don’t know why it did that. So since some of the code is still in the master branch, this is all that needs to be merged.

**Review by TonePoems — APPROVED** [review]
Question answered, comfortable with the changes

**Review by dburd08 — APPROVED** [review]
Looks good to me

**Pull request merged**
