### PR TITLE
6 upgraded sprinting for flying

### PR DESCRIPTION
**Pull request by TonePoems**
This ticket allows for modifiable flying speed, which is a bit different from the original ticket. Can explain the playtested reason for this difference

### CODE REVIEW

**Comment by TonePoems** [comment]
Had to resolve some weird merge conflicts over whitespace and one of my changes. No biggie

**Review by camaechi — APPROVED** [review]
I have reviewed your pull request and overall, the changes look great. You just need to update the readme file with the new controls

**Comment by TonePoems** [comment]
> 

I have updated the readme command to be accurate. Good catch, thanks!

**Review by dburd08 — APPROVED** [review]
Looks good and I see that the README was updated

**Pull request merged**
